In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import keras
from keras.models import Sequential
from keras.layers import Dense

In [2]:
#Import the Dataset
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:, 3:13].values
Y = dataset.iloc[:,13].values

In [3]:
label_encoder1= LabelEncoder()
X[:, 1]= label_encoder1.fit_transform(X[:, 1])
label_encoder2= LabelEncoder()
X[:, 2]= label_encoder1.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features= [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
#Splitting the dataset into training and testing
train_x, test_x,train_y, test_y = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [11]:
sc = StandardScaler()
train_x= sc.fit_transform(train_x)
test_x= sc.fit_transform(test_x)
train_x

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [13]:
#Initializing the ANN
classifier = Sequential()

In [15]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [16]:
# Adding the 2nd hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [17]:
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [18]:
#Compiling the ANN
classifier.compile(optimizer='adam', loss= 'binary_crossentropy' , metrics = ['accuracy'] )

In [20]:
# Fitting the ANN to the Training set
classifier.fit(train_x, train_y, batch_size=10, epochs = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 5s 594us/step - loss: 0.4954 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 2s 291us/step - loss: 0.4318 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 381us/step - loss: 0.4286 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 3s 414us/step - loss: 0.4267 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 4s 489us/step - loss: 0.4228 - acc: 0.8096
Epoch 6/100
8000/8000 [==============================] - ETA: 0s - loss: 0.4194 - acc: 0.822 - 4s 440us/step - loss: 0.4191 - acc: 0.8226
Epoch 7/100
8000/8000 [==============================] - 3s 436us/step - loss: 0.4164 - acc: 0.8242
Epoch 8/100
8000/8000 [==============================] - 3s 434us/step - loss: 0.4141 - acc: 0.8277
Epoch 9/100
8000/8000 [==============================] - 3s 364us/step - loss: 0.4132 - acc: 0.8309
Epoch 10/100
8

8000/8000 [==============================] - 2s 232us/step - loss: 0.4002 - acc: 0.8339
Epoch 79/100
8000/8000 [==============================] - 2s 231us/step - loss: 0.4014 - acc: 0.8356
Epoch 80/100
8000/8000 [==============================] - 2s 222us/step - loss: 0.4002 - acc: 0.8361
Epoch 81/100
8000/8000 [==============================] - 2s 290us/step - loss: 0.4010 - acc: 0.8336
Epoch 82/100
8000/8000 [==============================] - 2s 286us/step - loss: 0.4004 - acc: 0.8350
Epoch 83/100
8000/8000 [==============================] - 3s 317us/step - loss: 0.4007 - acc: 0.8369
Epoch 84/100
8000/8000 [==============================] - 2s 223us/step - loss: 0.4008 - acc: 0.8360
Epoch 85/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.4010 - acc: 0.8352
Epoch 86/100
8000/8000 [==============================] - 2s 265us/step - loss: 0.4008 - acc: 0.8352
Epoch 87/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.4011 - acc: 0.8361
Epo

In [21]:
# Predicting the Test set results
y_pred = classifier.predict(test_x)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [24]:
#Making the Confusion_Matrix
cm = confusion_matrix(test_y, y_pred)
cm

array([[1548,   47],
       [ 280,  125]], dtype=int64)

In [25]:
1548+125/2000

1548.0625